### ISSUE TITLE
Error Creating Wallet - Network error

### ISSUE THREAD

**Issue by erf** [NAVCoin/NavPay#107]
I tried to create a wallet using the latest NavPay release for MacOS (  NavPay-1.0.2b-osx.dmg ), and got the following error: "Cannot Create Wallet - Network error". I tried this a few times with no success.

I'm on a MacOS High Sierra version 10.13.1.

**Comment by Wildcatter** [comment]
I got the same error on MacOS.

Looks to be a Connection Refused error in the POST request to the API https://navpay.navcoin.org:3333/bws/api/v2/wallets/

**Comment by erf** [comment]
I tried it again now, and did not get the error anymore. The wallet is looking great btw! 😄
