### ISSUE TITLE
No NavCoin in NavPay Wallet

### ISSUE THREAD

**Issue by GloBronJames** [NAVCoin/NavPay#109]
Sent some NavCoin from the Nav Core wallet to the NavPay beta wallet on desktop. Still shows a balance of 0 in NavPay and says 'cannot update transaction history.'

- - -
[Elegantt data. What's this?](http://bit.ly/elegantt-for-trello-whats-this)
[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":false,"ownerId":false,"dependencies":[]})

**Comment by GloBronJames** [comment]
still dealing with the same issue 24+ hours later.

**Comment by craigmacgregor** [comment]
Can you try to import your wallet into the full release version which is available now?

If it doesn't work, please be as detailed as possible about the issue:

What device are you using it on?
What operating system?
What version of operating system?
Provide steps to reproduce the issue.
Provide screenshots.

**Of course, don't disclose any private information like your recovery phrase in your report or your screenshots.**

All these things help us to identify and resolve the issue as quickly as possible.
