### ISSUE TITLE
Wallet doesn't recover from passphrase 

### ISSUE THREAD

**Issue by frasaleksander** [NAVCoin/NavPay#113]
I've tried to recover my navpay wallet with passphrase but it displays "wallet not registered at the wallet service." or "502 error". I know that I am using legit passphrase, and I've also sent and received funds to that wallet without any problem. 

I've also tried to recreate it from "create personal wallet" using advanced options.  I've entered passphrase and it shows following message: "COPAYER_REGISTERED: Copayer ID already registered on server". -

This means that wallet already exists right? There are funds stuck on that wallet. I am sure I have correct passphrase

- - -
[Elegantt data. What's this?](http://bit.ly/elegantt-for-trello-whats-this)
[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":true,"ownerId":false,"dependencies":[],"psd":"2018-01-21T00:00:00+13:00","ped":"2018-01-21T07:30:00+13:00"})

**Comment by craigmacgregor** [comment]
To recover a wallet, you should just be able to click the + symbol on the home page on the title of the wallets listings, then import, then type in your recovery phrase.

<img width="762" alt="screen shot 2017-12-26 at 11 17 25 am" src="https://user-images.githubusercontent.com/6902746/34354489-de59fb1a-ea2e-11e7-8859-d3c1b0b5c1d6.png">
<img width="762" alt="screen shot 2017-12-26 at 11 17 36 am" src="https://user-images.githubusercontent.com/6902746/34354488-de42f280-ea2e-11e7-91b5-dd6a2c588389.png">
<img width="762" alt="screen shot 2017-12-26 at 11 17 41 am" src="https://user-images.githubusercontent.com/6902746/34354487-de2edc6e-ea2e-11e7-942d-cfcdd6473f7d.png">

I just recovered some wallets this way and it worked for me. However, we are experiencing heavy load on our backend server with more users on the wallet than we'd anticipated. So perhaps try it again this way now and report back whether it works for you or not. We are looking to upgrade the infrastructure behind the wallet as soon as possible.

If it doesn't work, please be as detailed as possible about the issue:

What device are you using it on?
What operating system?
What version of operating system?
Provide steps to reproduce the issue.
Provide screenshots.

All these things help us to identify and resolve the issue as quickly as possible.

**Comment by frasaleksander** [comment]
I had luck with recovering my other wallet. I've un-installed and cleared all the data on my phone. Still there is unsent transactions. I see that is sending funds and total locked balance of 22.49. Payment accepted but not yet broadcasted. Can I somehow cancel that? I have Delete payment proposal option

**Comment by craigmacgregor** [comment]
Hopefully this is resolved with a mongodb update on the back end.

Can you please close and re-open the application.
Then open the wallet to load the transactions.
If you still cant see them, try the: Settings -> Wallet -> More Options -> Wallet Addresses -> Scan addresses for funds.

Please let us know if this has worked, or if it hasn't provide more details as requested above.

**Comment by frasaleksander** [comment]
Everything is ok with that wallet again. But I am again missing funds from my main wallet. I've restarted my desktop app and rescanned for funds.Before maintenance I could see missing funds in my wallet again, but now it's the same. I am missing around 50 navcoins

**Comment by ro-savage** [comment]
@frasaleksander - If this is still an issue, please open a new issue or contact us on discord.
