### ISSUE TITLE
Lost much NAV coins with a small transaction using NavPay on android

### ISSUE THREAD

**Issue by Mollie2000** [NAVCoin/NavPay#114]
Hi,

I had a unconfirmed transaction sending 5 NAV and now almost half of all my coins are lost.

TX: https://chainz.cryptoid.info/nav/tx.dws?9b2af08a1444cc7a3d690069119864e2598b6c1ea0aa7a7e81630c048e395b97

I recreate my wallet using the web version, but nothing changed except with the web version i see the message: Could not update transaction history

- - -
[Elegantt data. What's this?](http://bit.ly/elegantt-for-trello-whats-this)
[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":true,"ownerId":false,"dependencies":[],"psd":"2018-01-21T07:30:00+13:00","ped":"2018-01-21T15:00:00+13:00"})

**Comment by frasaleksander** [comment]
I've sent 2nav to bittrex wallet. this happened: https://chainz.cryptoid.info/nav/tx.dws?9b15e9162ca7bb3c14869e59d660a200fcff3dae31730a8c9cb6743388dba800

**Comment by Mollie2000** [comment]
I have the address where my coins are!

**Comment by craigmacgregor** [comment]
To recover a wallet, you should just be able to click the + symbol on the home page on the title of the wallets listings, then import, then type in your recovery phrase.

<img width="762" alt="screen shot 2017-12-26 at 11 17 25 am" src="https://user-images.githubusercontent.com/6902746/34354489-de59fb1a-ea2e-11e7-8859-d3c1b0b5c1d6.png">
<img width="762" alt="screen shot 2017-12-26 at 11 17 36 am" src="https://user-images.githubusercontent.com/6902746/34354488-de42f280-ea2e-11e7-91b5-dd6a2c588389.png">
<img width="762" alt="screen shot 2017-12-26 at 11 17 41 am" src="https://user-images.githubusercontent.com/6902746/34354487-de2edc6e-ea2e-11e7-942d-cfcdd6473f7d.png">

I just recovered some wallets this way and it worked for me. However, we are experiencing heavy load on our backend server with more users on the wallet than we'd anticipated. So perhaps try it again this way now and report back whether it works for you or not. We are looking to upgrade the infrastructure behind the wallet as soon as possible.

If it doesn't work, please be as detailed as possible about the issue:

What device are you using it on?
What operating system?
What version of operating system?
Provide steps to reproduce the issue.
Provide screenshots.

**Of course, don't disclose any private information like your recovery phrase in your report or your screenshots.**

All these things help us to identify and resolve the issue as quickly as possible.

**Comment by craigmacgregor** [comment]
You could try to re-scan your wallet addresses:

Settings > Your Wallet > More Options > Wallet Addresses > Scan addresses for funds

If it doesn't work, please be as detailed as possible about the issue:

What device are you using it on?
What operating system?
What version of operating system?
Provide steps to reproduce the issue.
Provide screenshots.

**Of course, don't disclose any private information like your recovery phrase in your report or your screenshots.**

All these things help us to identify and resolve the issue as quickly as possible.

**Comment by Mollie2000** [comment]
Hi Craig,

Suddenly all my coins are back :)

The only thing not is showing the 5 NAV transaction in the history. My dad did received the 5 NAV but at this moment they dont show up in his wallet anymore. I guess we have to wait a little longer for those coins to show up again. He has the address (when you go to options ect.. in the app) of the 5 NAV coins in his wallet and are visible on the blockchain)

As you said, probably because of the heavy load on the server things are slowed down for the moment.

Thank you for the support. The support here, at reddit and discord is super! You all give me much confidence in NAV :)

**Comment by frasaleksander** [comment]
That unfortunately doesn't work for me. I should have 22(23) coins more in either mine or my dads wallet. My dads wallet is still empty and mine lacks those amount. Some of funds did indeed reshown on my personal desktop wallet, but not those funds. And i still cant recover my temporary (gifting) wallet

**Comment by craigmacgregor** [comment]
Hopefully this is resolved with a mongodb update on the back end.

Can you please close and re-open the application.
Then open the wallet to load the transactions.
If you still cant see them, try the: Settings -> Wallet -> More Options -> Wallet Addresses -> Scan addresses for funds.

Please let us know if this has worked, or if it hasn't provide more details as requested above.

**Comment by Mollie2000** [comment]
Im having again the same problem described above. 
Is there still a problem with the backend server?

**Comment by ro-savage** [comment]
@frasaleksander - Please open a new issue if you are still having problems.

I am closing this one for now.
