### ISSUE TITLE
Mac iSight camera stays active after switching from scanning screen

### ISSUE THREAD

**Issue by berendsrob** [NAVCoin/NavPay#116]
When selecting the scanning option, the camera stays active when you back to another screen. Most elegant way would be to show an 'activate camera' button on the scanning page, so you can proactively activate the camera AND know that it's active. 
Also, a button to inactivate and automatically inactivate the camera when you switch screen (or application) would add to the privacy feel NAV is trying to achieve...

- - -
[Elegantt data. What's this?](http://bit.ly/elegantt-for-trello-whats-this)
[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":true,"ownerId":false,"dependencies":[],"psd":"2018-01-21T22:30:00+13:00","ped":"2018-01-22T06:00:00+13:00"})

**Comment by ro-savage** [comment]
Thanks for the suggestions. This feature has been added by PR #144 and will be released in the near future.
