### ISSUE TITLE
IMPORTING NAV COINS TO NAVPAY FROM COINOMI WALLET

### ISSUE THREAD

**Issue by Treetins** [NAVCoin/NavPay#117]
It's been impossible to import my Nav coins from the troubled coinomi wallet using my phrase or private keys. It just doesn't respond as it should.
Can someone help with this please?

- - -
[Elegantt data. What's this?](http://bit.ly/elegantt-for-trello-whats-this)
[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":true,"ownerId":false,"dependencies":[],"psd":"2018-01-22T09:00:00+13:00","ped":"2018-01-23T02:08:34+13:00"})

**Comment by Yazanarki** [comment]
I have the same exact problem, very frustrating. . I read coinomi has a tool for 18 word passphrases and will try.

**Comment by Treetins** [comment]
You can access your Nav coins if you upgrade to the beta version 1.8 of the wallet. It worked for me.

**Comment by ro-savage** [comment]
Unfortunately can not provide support the Coinomi wallet. Please contact Coinomi directly.
