### ISSUE TITLE
Cant get my coins off of electrum

### ISSUE THREAD

**Issue by evannoel** [NAVCoin/NavPay#124]
So my old laptop has stopped working and I had a bunch of nav coins on the electrum wallet! now I bought  new laptop and see you cannot download electrum anymore. Is there any way anyone from nav team can help me I have the public key and the private key! please
thank you

**Comment by navtrello** [comment]
➤ Craig MacGregor commented:

If you have the private key from electrum, please follow the tutorial to move them into NavPay https://navcoin.org/news/electrum-export-to-navpay/

**Comment by evannoel** [comment]
Got them to nav pay! Thank you so much!

Sent from XFINITY Connect App



------ Original Message ------
