### ISSUE TITLE
Add ability to hide the "buy Nav" header card on the front page

### ISSUE THREAD

**Issue by navtrello** [NAVCoin/NavPay#130]
The fact that it hangs around with no way to hide it is annoying users, should be an easy fix.

[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":false,"ownerId":false,"dependencies":[]})

**Comment by ro-savage** [comment]
Closed by PR #144
