### ISSUE TITLE
Image assets need replacing

### ISSUE THREAD

**Issue by craigmacgregor** [NAVCoin/NavPay#2]
Bitcoin image assets need switching out for Nav Coin Branding.

Audit the images used in the project which need replacing.

Provide file paths to the assets we need to update inside the project.

Create new image assets as required.

**Comment by matt-auckland** [comment]
## MOBILE

- [ ] resources/copay/android/icon/drawable-ldpi-icon.png
- [ ] resources/copay/android/icon/drawable-mdpi-icon.png
- [ ] resources/copay/android/icon/drawable-hdpi-icon.png
- [ ] resources/copay/android/icon/drawable-xhdpi-icon.png
- [ ] resources/copay/android/icon/drawable-xxhdpi-icon.png
- [ ] resources/copay/android/icon/drawable-xxxhdpi-icon.png
- [ ] resources/copay/android/splash/drawable-land-hdpi-screen.png
- [ ] resources/copay/android/splash/drawable-land-ldpi-screen.png
- [ ] resources/copay/android/splash/drawable-land-mdpi-screen.png
- [ ] resources/copay/android/splash/drawable-land-xhdpi-screen.png
- [ ] resources/copay/android/splash/drawable-land-xxhdpi-screen.png
- [ ] resources/copay/android/splash/drawable-land-xxxhdpi-screen.png
- [ ] resources/copay/android/splash/drawable-port-hdpi-screen.png
- [ ] resources/copay/android/splash/drawable-port-ldpi-screen.png
- [ ] resources/copay/android/splash/drawable-port-mdpi-screen.png
- [ ] resources/copay/android/splash/drawable-port-xhdpi-screen.png
- [ ] resources/copay/android/splash/drawable-port-xxhdpi-screen.png
- [ ] resources/copay/android/splash/drawable-port-xxxhdpi-screen.png

- [ ] resources/copay/ios/icon/icon-60@3x.png
- [ ] resources/copay/ios/icon/icon-60.png
- [ ] resources/copay/ios/icon/icon-60@2x.png
- [ ] resources/copay/ios/icon/icon-76.png
- [ ] resources/copay/ios/icon/icon-76@2x.png
- [ ] resources/copay/ios/icon/icon-83.5@2x.png
- [ ] resources/copay/ios/icon/icon-40.png
- [ ] resources/copay/ios/icon/icon-40@2x.png
- [ ] resources/copay/ios/icon/icon@2x.png
- [ ] resources/copay/ios/icon/icon-72.png
- [ ] resources/copay/ios/icon/icon-72@2x.png
- [ ] resources/copay/ios/icon/icon-small.png
- [ ] resources/copay/ios/icon/icon-small@2x.png
- [ ] resources/copay/ios/icon/icon-small@3x.png
- [ ] resources/copay/ios/icon/icon-50.png
- [ ] resources/copay/ios/icon/icon-50@2x.png
- [ ] resources/copay/ios/splash/Default~iphone.png
- [ ] resources/copay/ios/splash/Default@2x~iphone.png
- [ ] resources/copay/ios/splash/Default-Portrait~ipad.png
- [ ] resources/copay/ios/splash/Default-Portrait@2x~ipad.png
- [ ] resources/copay/ios/splash/Default-Landscape~ipad.png
- [ ] resources/copay/ios/splash/Default-Landscape@2x~ipad.png
- [ ] resources/copay/ios/splash/Default-568h@2x~iphone.png
- [ ] resources/copay/ios/splash/Default-667h.png
- [ ] resources/copay/ios/splash/Default-736h.png
- [ ] resources/copay/ios/splash/Default-Landscape-736h.png

## Windows (not sure if for .exe or windows phone)
- [ ] resources/copay/windows/icon/StoreLogo.png
- [ ] resources/copay/windows/icon/Square30x30Logo.png
- [ ] resources/copay/windows/icon/Square44x44Logo.png
- [ ] resources/copay/windows/icon/Square70x70Logo.png
- [ ] resources/copay/windows/icon/Square71x71Logo.png
- [ ] resources/copay/windows/icon/Square150x150Logo.png
- [ ] resources/copay/windows/icon/Square310x310Logo.png
- [ ] resources/copay/windows/icon/Wide310x150Logo.png
- [ ] resources/copay/windows/splash/SplashScreen.png
- [ ] resources/copay/windows/splash/SplashScreen.scale-100.png
- [ ] resources/copay/windows/splash/SplashScreenPhone.scale-240.png
- [ ] resources/copay/windows/splash/splashscreenphone.png


## Other

- [ ] www/img/llustration-send-feedback.png
- [ ] www/img/icon-warning.png

- [ ] www/img/app/logo.png
- [ ] www/img/app/favicon.ico
- [ ] www/img/onboarding-tour-control.svg
- [ ] www/img/app/icon.png
- [ ] www/img/icon-chrome-128.png

## might be used with multisig wallets not sure  
- [ ] www/img/icon-bitcoin-white.svg

**Comment by craigmacgregor** [comment]
all done i think, testing build now.
