### ISSUE TITLE
Document Testing Plan

### ISSUE THREAD

**Issue by craigmacgregor** [NAVCoin/NavPay#22]
While we're doing this initial testing, we can capture what needs to be tested on our release candidates by the wider team.

Make a simple document with steps our testers should take.

**Comment by matt-auckland** [comment]
Work-In-progress:

# Testing Spec

## Functionality

### Regular wallet
- [ ] create wallet
- [ ] generate some valid addresses
- [ ] receive coins
- [ ] send coins
- [ ] delete wallet and use back-up phrase to restore wallet

### Multisig wallet
- [ ] create wallet
- [ ] generate some valid addresses
- [ ] receive coins
- [ ] send coins
- [ ] delete wallet and use back-up phrase to restore wallet

## Navigation

### Visit all tabs + sub menus
- [ ] Home

- [ ] Receive

- [ ] Send

- [ ] Scan

- [ ] Settings

### Check external links work

- [ ] Github issues
- [ ] Github link

**Comment by colvano** [comment]
Multisig wallet

- [x]    create wallet (this will require at least one other wallet to co-sign)
- [x]    generate some valid addresses
- [x]    receive coins
- [x]    send coins
- [x]    delete wallet and use back-up phrase to restore wallet
