### ISSUE TITLE
Android 7.1.1 NavTech servers not showing if user selects ''Max Amount''

### ISSUE THREAD

**Issue by juguelio** [NAVCoin/NavPay#31]
I found that the wallet won't connect to NavTech servers if user wants to send full amount of NAV's. It worked when I lowered the send.

**Comment by craigmacgregor** [comment]
Note that this is when using the Web Wallet on Android 7.1.1 but I suspect this issue would persist across devices and platforms.

**Comment by juguelio** [comment]
Yes you are right. It was Web Wallet. Sorry!
