### ISSUE TITLE
Windows Wallet nw_elf.dll Error doesn't open

### ISSUE THREAD

**Issue by Verrideo** [NAVCoin/NavPay#34]
When opening navpay-1.0.0-windows.exe you are immediately presented with the following error:
---------------------------
navpay-1.0.0-windows.exe - System Error
---------------------------
The program can't start because nw_elf.dll is missing from your computer. Try reinstalling the program to fix this problem. 
---------------------------
OK   
---------------------------

This has been tested on the following Windows OS's and is present on all 
Windows 10 64bit
Windows 7 64bit
Windows 2008 R2 Server 64bit
Windows 2012 R2 Server 64bit

**Comment by craigmacgregor** [comment]
this DLL is part of the compile output, ive uploaded a zip of the whole output directory. check discord channel for the link and please try again.

**Comment by craigmacgregor** [comment]
@Verrideo can you test this with the new zip when you get a chance and let me know if the issue is now resolved?

**Comment by Verrideo** [comment]
I can confirm this now works using the zip file downloaded from discord.
