### ISSUE TITLE
Scan function in Safari Browser - iOS

### ISSUE THREAD

**Issue by Bkbailey** [NAVCoin/NavPay#35]
When accessing the wallet from the safari browser on iOS, when you go to the scan function the camera will not turn on and freezes. Also it allows you to scroll on the page perhaps this should remain static?

- - -
[Elegantt data. What's this?](http://bit.ly/elegantt-for-trello-whats-this)
[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":false,"ownerId":false,"dependencies":[]})

**Comment by Bkbailey** [comment]
Safari browser in iOS 11.1 iPhone 7+ when trying to access the scan function. The page will ask for access to my camera. I click allow. The page will reload. Then the page just goes blank.

**Comment by craigmacgregor** [comment]
I'm taking over this bug since you cant use safari on your windows lappy @matt-auckland

**Comment by craigmacgregor** [comment]
https://github.com/bitpay/copay/issues/1207

**Comment by craigmacgregor** [comment]
<img width="1455" alt="screen shot 2017-11-04 at 10 21 01 pm" src="https://user-images.githubusercontent.com/6902746/32404102-82b0de94-c1ae-11e7-893b-b529a2e71b8e.png">

didnt work, their source is different to ours. could be to do with this cordova plugin not loading though.

**Comment by navtrello** [comment]
➤ Craig MacGregor commented:

having trouble figuring this one out. might have to do a peer session on this at some point @psanderson @matt36511783

**Comment by navtrello** [comment]
➤ Craig MacGregor commented:

resolved by adding browser detection and download link
