### ISSUE TITLE
Android 7.1.1 Scan code from other Android with NavPay

### ISSUE THREAD

**Issue by juguelio** [NAVCoin/NavPay#38]
When you scan a code from other mobile (I installed NavPay in a 2nd Android) It doesn't copy just the address but a: ''navcoin: N..........'' format
so then you need to copy the whole sentence to the clipboard, paste it into the send tab and then you need to remove the ''navcoin:''

I think it should be just the Nav address and go directly to send tab or save address

**Comment by craigmacgregor** [comment]
duplicate of issue #36
