### ISSUE TITLE
My bugs and some translation issues

### ISSUE THREAD

**Issue by IfaqYurmama** [NAVCoin/NavPay#40]
Tested on the Chrome extension

**General Fixes:**
•	Currency Alternative should put ~5 most used currencies (USD, EUR etc) at the top
•	When scanning a QR-Code adress in the send menu it should directly paste the adress into the send
•	Scrolling down in the transaction log stutters at the end
•	The search feature in the transaction log should be explained, it’s not clear what exactly you can and can not search for
•	Not chosing a backup warning shows BitPay (this was on the android app)

**German translations**

_Not translated:_

•	Settings -> Wallet -> Advanced -> Wallet Adresses: Explanation string not translated
•	Receive: Request specific amount string not translated
•	Receive: Generate new adress not translated
•	Send: Search or enter NavCoin adress not translated
•	Send: Private Payment -> Private Transaktion
•	Settings -> Wallet -> Advanced -> Wallet Service URL: Explanation string not translated
•	Home -> Recent Transactions -> Transaction -> Fee: x % of the transaction should be x% der Transaktion
•	Home -> Recent Transactions -> Transaction -> Fee -> View on blockchain: Title of popup window not translated, open cryptoID not translated

_Not ideal:_

•	Personal Wallet should be Translated as Persönliche Wallet not Persönliches Wallet
•	Settings -> Wallet -> Guthaben Verstecken should be Guthaben verstecken (lowercase v)
•	Settings -> Wallet -> Sicherung should stay Backup, Sicherung usually means fuse box
•	Settings -> Wallet -> Berechtigungscode abfragen should be Passwort or Passphrase
•	Settings -> Wallet -> Advance -> Public key should stay public key
•	Settings -> Advanced -> Unbestätigte Mittel einsetzen should be Unbestätigtes Guthaben einsetzen, Vermögen in the explanation text should also be changed to Guthaben
•	Settings -> Advanced -> Kürzlich Ausgeführte Transaktionen Karte makes no sense at all, should either be Kürzliche Transaktionen anzeigen or „Kürzliche Transaktionen“-Widget anzeigen
•	Settings -> Advanced -> Nächste Schritte Karte Anzeigen should be Tutorials anzeigen or Tutorials-Widget anzeigen
•	Home -> Recent Transactions -> Keine aktuellen Transaktionen should be keine kürzlichen Transaktionen

**Comment by craigmacgregor** [comment]
•	Currency Alternative should put ~5 most used currencies (USD, EUR etc) at the top
Feature request #41 

•	When scanning a QR-Code adress in the send menu it should directly paste the adress into the send
Duplicate #36 

•	Scrolling down in the transaction log stutters at the end
Can you please provide more info on #42

•	The search feature in the transaction log should be explained, it’s not clear what exactly you can and can not search for

•	Not chosing a backup warning shows BitPay (this was on the android app)
#43

**Comment by matt-auckland** [comment]
I have added the translation issues to #61 . Going to close this ticket as we've split all the parts out into other tickets
