### ISSUE TITLE
Currency Alternative should put ~5 most used currencies (USD, EUR etc) at the top

### ISSUE THREAD

**Issue by craigmacgregor** [NAVCoin/NavPay#41]
Feature request

- - -
[Elegantt data. What's this?](http://bit.ly/elegantt-for-trello-whats-this)
[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":true,"ownerId":false,"dependencies":[],"psd":"2017-11-24T10:30:00+13:00","ped":"2017-11-24T12:00:00+13:00"})

**Comment by juguelio** [comment]
Adding to that, GBP is called ''Pound Sterling'' in the app, although the official name, on most of the currency options GBP is usually called as: ''Great Britain Pound. It took me a while to find the right currency.

**Comment by matt-auckland** [comment]
Breaking @juguelio 's comment out into it's own ticket

**Comment by PhillipJFryz** [comment]
test
