### ISSUE TITLE
Scrolling down in the transaction log stutters at the end

### ISSUE THREAD

**Issue by craigmacgregor** [NAVCoin/NavPay#42]
Can we get some more information about this?

Operating System, Version, Screen shot of the page.

**Comment by IfaqYurmama** [comment]
This happened on the chrome extension. I made a crappy video with my phone yesterday, I hope you can see it: https://www.youtube.com/watch?v=j4Ry8ccYhRs

If you change the playback speed to 0.5 you see it bounces back a bit when at the end. This makes it stutter and looks weird.

OS Windows 10
Chrome 61.0

**Comment by craigmacgregor** [comment]
Closing issue as its pretty minor and chrome apps are being deprecated by google.
