### ISSUE TITLE
Settings -> Share NavPay: Shares a bitpay link, sometimes buggy

### ISSUE THREAD

**Issue by IfaqYurmama** [NAVCoin/NavPay#55]
https://streamable.com/2ey0c

The shares link needs to be changed.

When using the twitter share option it locks the app before you are taken to twitter.

Also suggesting to ditch G+ and add facebook iinstead.

**Comment by matt-auckland** [comment]
I'm unable to replicate your issue (incorrect text for sharing and the fingerprint scan issue), which version of the beta do you have installed? 1.0.0 or 1.0.1?
Is your wallet encrypted and secured with a password?
Do you have the Facebook app installed? I think these icons only show for what apps you have installed.

**Comment by matt-auckland** [comment]
I've updated the sharing page's text to reflect that it only uses your installed apps.
I've also fixed the shared text.

**Comment by IfaqYurmama** [comment]
Just installed 1.0.2, seems to work now.
