### ISSUE TITLE
Tittle of the App in Osx.

### ISSUE THREAD

**Issue by juguelio** [NAVCoin/NavPay#56]
Tittle should match core wallet.
Take a look to the screenshot.

NavCoin Core
Navpay

<img width="204" alt="screen shot 2017-11-03 at 20 09 03" src="https://user-images.githubusercontent.com/25780758/32393864-1707efd8-c0d3-11e7-887d-9f9b46f7ab93.png">

**Comment by craigmacgregor** [comment]
NavPay ?

**Comment by IfaqYurmama** [comment]
I agree, NavPay looks better
