### ISSUE TITLE
Changelly exchange inside the app

### ISSUE THREAD

**Issue by craigmacgregor** [NAVCoin/NavPay#64]
Add Changelly to the app to enable users to direct buy within the app.

When you have no balance and click send it shows you a card about buying NAV.

* [x] Remove card icon
* [x] Remove "show address" button 
* [x] Reword text "To get started, you can buy Nav Coin through our exchange partner Changelly."

Show this card always on the home screen (until we decide on a better UI) as well as on this no nav send screen.

When the "Buy Nav Coin" button is clicked, take them to a new page which shows:

* [x] Changelly widget with our referral code and BTC/NAV pair
* [x] Latest NAV address that can be clicked to copy, so the user can paste it into the changelly widget. Ideally it would look like the attached NAV Address screen shot but be clickable to copy.
* [x] regular navigation at the bottom of the screen.

The rest should be handled by changelly.

- - -
[Elegantt data. What's this?](http://bit.ly/elegantt-for-trello-whats-this)
[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":true,"ownerId":false,"dependencies":[],"psd":"2017-11-24T21:00:00+13:00","ped":"2017-11-24T22:30:00+13:00"})

**Comment by matt-auckland** [comment]
![screenshot_20171110-111950](https://user-images.githubusercontent.com/12672050/32632693-716b3bac-c609-11e7-9567-da825f951ce7.png)

**Comment by craigmacgregor** [comment]
![img_20171110_112321](https://user-images.githubusercontent.com/6902746/32632768-b9fa2a40-c609-11e7-96ea-98ecbf8f1c32.jpg)

**Comment by craigmacgregor** [comment]
![screenshot_20171110-112720](https://user-images.githubusercontent.com/6902746/32632903-3c0fe5ec-c60a-11e7-8226-4709e4a557a2.png)

**Comment by craigmacgregor** [comment]
<iframe src="https://changelly.com/widget/v1?auth=email&from=USD&to=NAV&merchant_id=fa6a4eb25086&address=&amount=20&ref_id=6c2996558a71&color=7d59b5" width="600" height="500" class="changelly" scrolling="no" style="overflow-y: hidden; border: none" > Can't load widget </iframe>

**Comment by craigmacgregor** [comment]
get iframe to scale to mobile size somehow.
