### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by aguycalled** [NAVCoin/NavPay#65]
- - -
[Elegantt data. What's this?](http://bit.ly/elegantt-for-trello-whats-this)
[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":true,"ownerId":false,"dependencies":[],"psd":"2017-11-24T22:30:00+13:00","ped":"2017-11-25T00:00:00+13:00"})

**Comment by navtrello** [comment]
➤ Matt commented:

Not sure if we actually planned anything for this. (We have no specs written for it or anything), so I'm just going to remove it. Anything this would cover is covered by the general translation stuff I'm doing
