### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by craigmacgregor** [NAVCoin/NavPay#68]
Cloning the beta branch and running "npm run apply:copay" causes a build error.

To hack around this, checkout master

run "rm -rf node_modules bower_components"
run "npm run apply:copay"

switch to beta and run "npm run apply:copay"

need to figure out why the beta branch wont compile from fresh.

- - -
[Elegantt data. What's this?](http://bit.ly/elegantt-for-trello-whats-this)
[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":false,"ownerId":false,"dependencies":[]})

**Comment by navtrello** [comment]
➤ Craig MacGregor commented:

I can get the beta-1.0.4 branch to build from fresh checkout
