### ISSUE TITLE
Windows Wallet - Typo Transaction History Screen

### ISSUE THREAD

**Issue by Verrideo** [NAVCoin/NavPay#70]
There is a typo in the transaction history screen in the information for the clear cache option.

says "clear" when I think it should be "clears"

**Comment by matt-auckland** [comment]
If you're talking about the English version, then "Clear Cache" is correct. Closing this issue.

**Comment by Verrideo** [comment]
No sorry I stupidly made a typo in my message about the typo haha :). There is some text at the bottom of the screen in that windows under the "clear cache" heading. The text reads as follows:

"The transaction history and every new incoming transaction are cached in the app. This feature clean this up and synchronizes again from the server" 

I think this should read "cleans this up" instead of "clean"

**Comment by matt-auckland** [comment]
Will get on this

**Comment by matt-auckland** [comment]
fixed
