### ISSUE TITLE
Windows Wallet - No Notification Options 

### ISSUE THREAD

**Issue by Verrideo** [NAVCoin/NavPay#73]
When going into the notification options on the windows wallet nothing is displayed

Would be nice to get notifications of payments sent and received like in the core wallet

If not possible
Suggest removing option where not needed or maybe displaying informative message stating no options can be set here.

**Comment by matt-auckland** [comment]
Disabling the notifications menu in desktop for now. May look to add notifications in the future.
See https://github.com/NAVCoin/NavPay/issues/88
