### ISSUE TITLE
Deleting of wallet no password prompt Improvement 

### ISSUE THREAD

**Issue by Verrideo** [NAVCoin/NavPay#74]
When deleting a wallet which has a sending password on it there is no prompt to enter the password. This seems insecure.

Suggest making users enter sending password to delete ad password protected wallet.

**Comment by matt-auckland** [comment]
My only issue with this is if someone forgets the password, they can't remove the wallet.
Technically you should have the wallet backed up if you have a spending password, so if you lose it you can restore it.

**Comment by navtrello** [comment]
➤ Craig MacGregor commented:

Closing this issue as per Matt's recommendation
