### ISSUE TITLE
Trapped on Nav Website

### ISSUE THREAD

**Issue by Verrideo** [NAVCoin/NavPay#75]
When initially running the wallet and entering the sending section before wallet has a balance.

If you click "Buy Nav Coin" you get forwarded through to the NAV website but then become trapped there with no way of getting back into the wallet UI without restarting.

**Comment by Verrideo** [comment]
Only tested on windows wallet

**Comment by craigmacgregor** [comment]
get the link to open in new tab

**Comment by matt-auckland** [comment]
fixed
