### ISSUE TITLE
Windows Wallet - No Navtech Transactions 

### ISSUE THREAD

**Issue by Verrideo** [NAVCoin/NavPay#76]
When trying to send private payments on the windows wallet you receive the error message:
"Could not connect to NavTech servers. Only normal transactions are available right now." 

Tried a few times today on windows 7 and 2012 r2 and fails all the time. Can receive private payments fine.

- - -
[Elegantt data. What's this?](http://bit.ly/elegantt-for-trello-whats-this)
[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":true,"ownerId":false,"dependencies":[],"psd":"2017-11-25T01:30:00+13:00","ped":"2017-11-25T03:00:00+13:00"})

**Comment by craigmacgregor** [comment]
What version are you on? v1.0.2, commit hash #b8028ca ?

<img width="631" alt="screen shot 2017-11-10 at 10 44 38 am" src="https://user-images.githubusercontent.com/6902746/32631136-2bf46238-c604-11e7-98af-82fb93701cf0.png">

**Comment by matt-auckland** [comment]
@Verrideo Is this still an issue for you?

**Comment by Verrideo** [comment]
Sorry guys i didn't spot the update on this one. Should he able to test this again with the newer release this evening and will update on the out outcome.

**Comment by Verrideo** [comment]
I can confirm this is now working fine on the new 1.0.3b release on various windows flavors
