### ISSUE TITLE
Crash adjusting "Fee: Priority" option

### ISSUE THREAD

**Issue by Verrideo** [NAVCoin/NavPay#77]
Tested on windows wallet on windows 7, windows 2012 r2, windows 2008 r2 

When using "send max amount" option to send coins. on the next screen if you then try and adjust the "Fee: Priority" option the wallet crashes irrecoverably and a restart is required.

**Comment by craigmacgregor** [comment]
disabling the fee as its not necessary to use a custom fee for our blockchain.
