### ISSUE TITLE
Recent Transactions only show sent payments

### ISSUE THREAD

**Issue by Verrideo** [NAVCoin/NavPay#78]
Tested only on Windows 10, Windows 2012 R2 

Recent Transactions card on the home screen only displays recent SENT transactions and not received. If this is deliberate the wording should be changed as it is mis-leading

**Comment by matt-auckland** [comment]
This section actually shows a number of things:
* Outgoing transactions
* Incoming transactions
* Deleted transaction proposals
* Rejected transaction proposals
* New transaction proposals
* Info on transaction proposal acceptions

That being said, I think it's probably worth changing the title of this section
