### ISSUE TITLE
Banner title text consistency update on Windows and Chrome

### ISSUE THREAD

**Issue by bocyaj** [NAVCoin/NavPay#80]
I think the banner title needs an update on both Windows NavPay and Chrome extension.  Cant confirm what is on other releases.

Current title banner on Windows:
 
![image](https://user-images.githubusercontent.com/19207801/32494085-450aac5a-c38e-11e7-9a0c-aec7191d0e12.png)
suggest change to "NavPay - Nav Coin thin Wallet"  * or use lite instead of thin.

current title banner on Chrome extension:
![image](https://user-images.githubusercontent.com/19207801/32494128-785cfdec-c38e-11e7-809b-26edbd1903c4.png)
suggest adding "NavPay - Nav Coin thin Wallet"  * or use lite instead of thin.

EXTRA: could also update the Nav Coin Core Wallet.(would you prefer seperate issue opened in Navcoin-core section?)
![image](https://user-images.githubusercontent.com/19207801/32494204-c12a88dc-c38e-11e7-8abe-fb42014e6c70.png)
suggest change to "NavCore - Nav Coin Full Node Wallet"   *also update logo to match NavPay

Essentially having a consistent banner title is what I think should be done, whether my suggestions are used is up to the team.

Cheers,
Bocyaj.

**Comment by craigmacgregor** [comment]
update the site title in the index.html "Nav Pay - Nav Coin Thin Client"

**Comment by matt-auckland** [comment]
done
