### ISSUE TITLE
Enter amount currency selection button update enhancement

### ISSUE THREAD

**Issue by bocyaj** [NAVCoin/NavPay#81]
Suggest changing the currency selection button on found on all of the "Enter Amount" pages.

![image](https://user-images.githubusercontent.com/19207801/32494755-e745e438-c390-11e7-831f-73f2f81d4172.png)

I did not realize I could switch the currency between CAD and NAV at first.  

Suggest having a button kind of like this to emphasize that the balance can be switched between currency type:
![image](https://user-images.githubusercontent.com/19207801/32494708-ac632434-c390-11e7-9e30-d091e48a8f06.png)

or (have the selected currency highlighted in purple)
![image](https://user-images.githubusercontent.com/19207801/32494730-c9a4da92-c390-11e7-8073-533450dd59ec.png)

**Comment by Verrideo** [comment]
I has considering this one myself as well. Took me a bit to realise that you had to click it to change, it wasn't obvious enough for the end users.

**Comment by matt-auckland** [comment]
done
