### ISSUE TITLE
Branding update for Windows icon

### ISSUE THREAD

**Issue by bocyaj** [NAVCoin/NavPay#82]
The application icon in Windows is not branded as Nav Coin, it shows up like this now:
![image](https://user-images.githubusercontent.com/19207801/32495153-6c09f730-c392-11e7-8645-bc96e4787eea.png)

It displays this icon when the application is pinned to start menu and the executable file icon is the same.

Guessing the installer version of the wallet would address this, but just in case it was overlooked, opened the issue.

**Comment by matt-auckland** [comment]
http://docs.nwjs.io/en/latest/For%20Users/Package%20and%20Distribute/#windows

**Comment by bocyaj** [comment]
Update from the public beta release.

The icon that gets added to start menu during the install is proper now:
![image](https://user-images.githubusercontent.com/19207801/32664102-36b172ac-c5fe-11e7-9bb0-5428a332571e.png)

if I do this manually via right cilck the exe file and 'pin to start menu', the icon is good now as well:
![image](https://user-images.githubusercontent.com/19207801/32664196-8d1ba202-c5fe-11e7-9922-3aee0adeeb67.png)

However, the exe file itself still remains as it was before:
![image](https://user-images.githubusercontent.com/19207801/32664263-b7cee0b8-c5fe-11e7-902c-62559b81cf51.png)

I will ask others to see what they are experiencing as I find it odd that my results are different this time.

**Comment by matt-auckland** [comment]
Completed.
We now assign the right icon to the exe so there should be no issues with an incorrect icon
