### ISSUE TITLE
Android 4.1.1 When Scanning QT normal send by default. 

### ISSUE THREAD

**Issue by juguelio** [NAVCoin/NavPay#83]
It should give the option for private send as well.

**Comment by craigmacgregor** [comment]
When scanning from the navigation button, if the user clicks "Send payment to this address", they should be sent to the tab-send route, rather than straight to the amount screen. You can add the address as a URL param to get it to auto fill into the input.

**Comment by craigmacgregor** [comment]
This is done, will be in the next release build
