### ISSUE TITLE
Changelly box bad rendering on Android

### ISSUE THREAD

**Issue by juguelio** [NAVCoin/NavPay#91]
Please look at the image:

![screenshot!UNITO-UNDERSCORE!20171116-161814](https://user-images.githubusercontent.com/25780758/32902355-161f8466-caea-11e7-827f-5ce2cf7305da.png)

- - -
[Elegantt data. What's this?](http://bit.ly/elegantt-for-trello-whats-this)
[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":false,"ownerId":false,"dependencies":[]})

**Comment by craigmacgregor** [comment]
@juguelio what device is this on? Do you know the pixel dimensions of your screen?

**Comment by juguelio** [comment]
One plus 5 1080p 5.5 inches

**Comment by craigmacgregor** [comment]
Same issue on Honor 5X with a 5.5 inch screen full hd (1080 x 1920)

**Comment by colvano** [comment]
Same issue HTC One 5.2 inch 2560x1440

**Comment by juguelio** [comment]
Similar issue with version 1.0.4. Look top borders.
![screenshot_20171122-201649](https://user-images.githubusercontent.com/25780758/33148131-859942d2-cfc2-11e7-8064-fbffe9ae2663.png)

**Comment by navtrello** [comment]
➤ Craig MacGregor commented:

re-opening ticket

**Comment by navtrello** [comment]
➤ Craig MacGregor commented:

Flex Box, Center / Center and some scaling
