### ISSUE TITLE
Feature List for Marketing

### ISSUE THREAD

**Issue by craigmacgregor** [NAVCoin/NavPay#94]
- - -
[Elegantt data. What's this?](http://bit.ly/elegantt-for-trello-whats-this)
[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":true,"ownerId":false,"dependencies":[],"psd":"2017-11-13T09:00:00+13:00","ped":"2017-11-17T18:00:00+13:00"})

**Comment by navtrello** [comment]
➤ Matt commented:

Big Tickets
  * NavTech Transactions
  * Multi Sig wallets (multiple people share a wallet and a certain % of them have to agree on transactions)
  * Changelly integration
  * Multi-platform (Android, iOS, Linux, OSX, Web, Windows, Chrome App)
  * Wallet encryption

Small Fish
  * Address book (you can save addresses)
  * QR Scanner
  * Seed phrase back up

**Comment by navtrello** [comment]
➤ Craig MacGregor commented:

can use fingerprint to unlock on moblie
