### ISSUE TITLE
Investigate Translations

### ISSUE THREAD

**Issue by navtrello** [NAVCoin/NavPay#97]
Flick through all supported languages and document which items are not translated due to being our own additions to the text. Organise with Kieren to do possible bounties for these translations. Google Translate if we cant find people to do it.

Hide button for contributing to language translations. inside the settings > choose language.

- - -
[Elegantt data. What's this?](http://bit.ly/elegantt-for-trello-whats-this)
[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":false,"ownerId":false,"dependencies":[],"ped":"2017-12-05T12:00:00+13:00"})

**Comment by navtrello** [comment]
➤ Matt commented:

Missing translations:

  * Frontpage Changelly 'card' needs translating.
  * send screen "Private Payment" and Next button
  * changelly screen "loading changelly" text

**Comment by navtrello** [comment]
➤ Matt commented:

Required translations are listed in a google doc. They're being filled in by the community.

**Comment by navtrello** [comment]
➤ Matt commented:

Waiting on the Korean translation, as well as lines about the changelly widget loading in: Spanish, Polish, Russian.

**Comment by PhillipJFryz** [comment]
changelly widget loading : changelly widget 실행 중
